---
title: "VDJ sequencing - HUSTLE-Seq - Clonotype info"
output:
  html_document:
    df_print: paged
  pdf_document: default
  toc: TRUE
---

```{r, echo = F}
knitr::opts_chunk$set(warning = F, message = F)
# knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
#knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=8) 

```

Cells with assigned clonotypes

```{r}

add_clonotype <- function(seurat_obj){
    tcr <- read.csv(paste0("../Data/", lib_name, "/filtered_contig_annotations.csv"))
    # Clonotype-centric info.
    clono <- read.csv(paste0("../Data/", lib_name, "/clonotypes.csv"))

    # Subsets so only the first line of each barcode is kept,
    # as each entry for given barcode will have same clonotype.
    tcr <- tcr %>% 
      distinct(barcode, .keep_all = T) %>% 
      # Only keep the barcode and clonotype columns. 
      # We'll get additional clonotype info from the clonotype table.
      dplyr::select(barcode, raw_clonotype_id) %>% 
      rename(clonotype_id = raw_clonotype_id) %>% 
      # Slap the AA sequences onto our original table by clonotype_id.
      merge(., clono[, c("clonotype_id", "cdr3s_aa")]) %>% 
      tibble::column_to_rownames("barcode")
    
    seurat_obj <- seurat_obj[,rownames(tcr)]
    
    # Add to the Seurat object's metadata.
    clono_seurat <- AddMetaData(object=seurat_obj, metadata=tcr)
    return(clono_seurat)
}

Idents(hustle) <- rownames(hustle@meta.data)
hustle <- add_clonotype(hustle)

table(!is.na(hustle$clonotype_id))
meta <- hustle@meta.data %>% 
  tibble::rownames_to_column("Cell")
write.table(meta, "Proliferated_L2_metadata.txt", row.names = F, quote = F)
# FALSE  TRUE 
#   515   834
```

```{r}
# keep only the clonotypes

hustle <- subset(hustle, cells = colnames(hustle)[!is.na(hustle$clonotype_id)])
hustle
```

<!-- ```{r} -->
<!-- Idents(hustle) <- "clonotype_id" -->
<!-- RidgePlot(hustle, features="nCount_RNA") + theme(axis.text.y = element_blank()) + NoLegend() -->
<!-- RidgePlot(hustle, features="nfeature_RNA") + theme(axis.text.y = element_blank()) + NoLegend() -->
<!-- RidgePlot(hustle, features="percent.mt") + theme(axis.text.y = element_blank()) + NoLegend() -->
<!-- ``` -->

```{r}
Idents(hustle) <- "HTO_maxID"
RidgePlot(hustle, assay = "HTO", features = rownames(hustle@assays[["HTO"]])[1:6])
RidgePlot(hustle, assay = "HTO", features = rownames(hustle@assays[["HTO"]])[7:12])
```


```{r}
# Variable genes, cell cycle regression; ribosomal expression regression; principal components from elbow plot
# hustle <- NormalizeData(hustle, normalization.method = "LogNormalize", scale.factor = 10000)
# s.genes <- cc.genes$s.genes
# g2m.genes <- cc.genes$g2m.genes
# hustle <- CellCycleScoring(hustle, g2m.features = g2m.genes, s.features = s.genes)

# hustle <- FindVariableFeatures(hustle, selection.method = "vst", nfeatures = 2000)
# all.genes <- rownames(hustle)
# hustle <- ScaleData(hustle) #, features = all.genes
# hustle <- RunPCA(hustle)
# ElbowPlot(hustle)
# VizDimLoadings(hustle, dims = 1:2, reduction = "pca")
# DimHeatmap(hustle, dims = 1:5, cells = 500, balanced = TRUE)
# hustle <- FindNeighbors(hustle, dims = 1:12)
# hustle <- FindClusters(hustle, resolution = 0.8)
# hustle <- RunUMAP(hustle, dims = 1:12, reduction = "pca")

# Identify the 15 most highly variable genes
# ranked_variable_genes <- VariableFeatures(hustle)
# top_genes <- ranked_variable_genes[1:15]

### ribo module score
# hustle <- AddModuleScore(
#   object = hustle,
#   features = ribo.genes,
#   name = 'RiboScore'
#   )
# FeaturePlot(hustle, features = "RiboScore1")

# Plot the average expression and variance of these genes
# With labels to indicate which genes are in the top 15
# p <- VariableFeaturePlot(hustle)
# LabelPoints(plot = p, points = top_genes, repel = TRUE)
# hustle <- RunPCA(hustle, features = VariableFeatures(object = hustle))
# DimPlot(hustle,
#         reduction = "pca",
#         group.by= "Phase")
# hustle <- ScaleData(hustle, vars.to.regress = c("S.Score", "G2M.Score"), features = rownames(hustle))
# hustle <- RunPCA(hustle, features = VariableFeatures(object = hustle), npcs = 15, nfeatures.print = 10)
# DimPlot(hustle, reduction = "pca", group.by = "Phase")
# hustle <- RunPCA(hustle, features = c(s.genes, g2m.genes), npcs = 15)
# DimPlot(hustle, reduction = "pca", group.by = "Phase")
# hustle <- ScaleData(hustle, vars.to.regress = c("percent.ribo"), features = rownames(hustle))
# hustle <- RunPCA(hustle, features = c(ribo.genes), npcs = 15)
# Idents(hustle) <- "RiboScore1"
# DimPlot(hustle, reduction = "pca") + NoLegend()
#hustle <- SCTransform(hustle, vars.to.regress = c("S.Score", "G2M.Score", "percent.ribo"))
#hustle <- SCTransform(hustle, vars.to.regress = c("S.Score", "G2M.Score"))
# hustle <- JackStraw(hustle, num.replicate = 70)
# hustle <- ScoreJackStraw(hustle, dims = 1:10)
#JackStrawPlot(hustle, dims = 1:10)
```

```{r}
use.pcs = 1:17
8482 -> saved.seed
hustle <- NormalizeData(hustle, normalization.method = "LogNormalize", scale.factor = 10000)
hustle <- FindVariableFeatures(hustle, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(hustle)
hustle <- ScaleData(hustle) #, features = all.genes
hustle <- RunPCA(hustle)
hustle <- RunTSNE(hustle, dims=use.pcs, seed.use = saved.seed, perplexity=100)
ElbowPlot(hustle)
VizDimLoadings(hustle, dims = 1:2, reduction = "pca")
DimHeatmap(hustle, dims = 1:5, cells = 500, balanced = TRUE)
hustle <- FindNeighbors(hustle, dims = use.pcs)
hustle <- RunUMAP(hustle, dims = use.pcs, reduction = "pca")
hustle <- FindClusters(hustle, resolution = 1) #,  graph.name = "RNA_snn_res.0.9"
DimPlot(hustle, reduction = "umap")
```


```{r}
#png("HUSTLEseq_cellcycle_ambientRNA_PCs.png", width = 9, height = 5)
#DimHeatmap(hustle, dims = 1:5, nfeatures = 30)
#dev.off()
```


```{r}
FeaturePlot(hustle, feature = "MKI67", reduction = "umap")
```



<!-- T- and B-cell markers -->
<!-- ```{r} -->

<!-- t_cell_markers <- c("CD3D","CD3E") -->
<!-- b_cell_markers <- c("CD79A", "CD79B") -->
<!-- FeaturePlot(hustle, features = t_cell_markers) -->
<!-- FeaturePlot(hustle, features = b_cell_markers) -->

<!-- #table(!is.na(hustle$clonotype_id),hustle$seurat_clusters) -->
<!-- ``` -->

Gene markers for clusters
```{r}
markers_all = FindAllMarkers(hustle,genes.use = VariableFeatures(hustle),
    only.pos = F, 
    min.pct = 0.25, 
    thresh.use = 0.25)
DT::datatable(markers_all)
```

Gene markers unique to each cluster
```{r}
markers_all_single <- markers_all[markers_all$gene %in% names(table(markers_all$gene))[table(markers_all$gene) == 1],]
DT::datatable(markers_all_single)
```

Top N marker genes
```{r}
top15_markers <- markers_all %>% 
  group_by(cluster) %>% 
  slice_max(n = 20, order_by = abs(avg_log2FC))

DT::datatable(top15_markers)

top10 <- markers_all %>% group_by(cluster) %>% top_n(10, avg_log2FC)
#FeaturePlot(hustle, features = top10$gene[6:10])

```

Visualise cells with assigned clonotypes, predicted celltypes and cell clusters
```{r}
hustle <- RunAzimuth(hustle, reference = "pbmcref")
DimPlot(hustle, reduction = "umap", group.by = "clonotype_id", label = F) + NoLegend()
DimPlot(hustle, reduction = "umap", group.by = "predicted.celltype.l2", label = T)
#DimPlot(hustle, reduction = "umap", label = TRUE)
#ggsave("HUSTLEseq_cellcycle_ambientRNA_clusters.png", width = 9, height = 5)
```

Heatmap with top 10 markers
```{r}
DoHeatmap(
    object = hustle, 
    features = top10$gene
) + 
    theme(text = element_text(size = 8))
#ggsave("HUSTLEseq_cellcycle_ambientRNA_markergenes_heatmap.png", width = 12, height = 9)

# write.table(top15_markers, "hustleseq_top15_markers_6clusters.txt", row.names = F, quote = F)
# write.table(markers_all_single, "hustleseq_unique_markers_6clusters.txt", row.names = F, quote = F)
```


Cells mapped to specific epitopes
```{r}

# hustle.meta <- data.frame(hustle@reductions[["umap"]]@cell.embeddings) %>%
#   tibble::rownames_to_column("Cell") %>%
#   mutate(clonotype_id = substr(hustle@meta.data$clonotype_id, 9, nchar(hustle@meta.data$clonotype_id))) %>%
#   mutate(clone_colour = case_when(
#     clonotype_id == "clonotype1" ~ "cornflowerblue",
#     clonotype_id == "clonotype2" ~ "cornflowerblue",
#     clonotype_id == "clonotype4" ~ "salmon",
#     clonotype_id == "clonotype6" ~ "lightgreen",
#     clonotype_id == "clonotype9" ~ "navyblue",
#     clonotype_id == "clonotype24" ~ "darkred",
#     clonotype_id == "clonotype43" ~ "yellow4",
#     .default = "gray80"
#   )) %>%
#   mutate(peptide.pool = hustle$pep.pool) %>%
#   mutate(pep.pool.colour = case_when(
#     peptide.pool == "P1" & clone_colour != "gray80" ~ "#440154",
#     peptide.pool == "P2" & clone_colour != "gray80" ~ "#472d7b",
#     peptide.pool == "P3" & clone_colour != "gray80" ~ "#3b528b",
#     peptide.pool == "P4" & clone_colour != "gray80" ~ "#2c728e",
#     peptide.pool == "P5" & clone_colour != "gray80" ~ "#21918c",
#     peptide.pool == "P6" & clone_colour != "gray80" ~ "#28ae80",
#     peptide.pool == "P7" & clone_colour != "gray80" ~ "#5ec962",
#     peptide.pool == "P8" & clone_colour != "gray80" ~ "#addc30",
#     peptide.pool == "P9" & clone_colour != "gray80" ~ "#fde725",
#     .default = "gray80"
#   ))
# 
# ggplot(hustle.meta, aes(umap_1, umap_2, label = clonotype_id,), colour = clonotype_id) +
#   geom_point(size = 2, alpha = 0.8, colour = hustle.meta$clone_colour) +
#   theme_bw() +
#   theme(legend.position = "right")
# #ggsave("HUSTLEseq_cellcycle_ambientRNA_clonotypesOfInterest.png", width = 9, height = 7)
# 
# hustle.meta1 <- data.frame(hustle@reductions[["umap"]]@cell.embeddings) %>%
#   tibble::rownames_to_column("Cell") %>%
#   mutate(clonotype_id = substr(hustle@meta.data$clonotype_id, 9, nchar(hustle@meta.data$clonotype_id))) %>%
#   mutate(clone_colour1 = case_when(
#     clonotype_id == "clonotype1" ~ "cornflowerblue",
#     .default = "gray80"
#   )) %>%
#   mutate(peptide.pool = hustle$pep.pool) %>%
#   mutate(pep.pool.colour1 = case_when(
#     peptide.pool == "P1" & clone_colour1 != "gray80" ~ "#440154",
#     .default = "gray80"
#   ))
# 
# ggplot(hustle.meta1, aes(umap_1, umap_2, label = clonotype_id,), colour = clonotype_id) +
#   geom_point(size = 2, alpha = 0.8, colour = hustle.meta1$clone_colour1) +
#   theme_bw() +
#   theme(legend.position = "right")
# #ggsave("HUSTLEseq_cellcycle_ambientRNA_clonotype1.png", width = 9, height = 7)

```

Peptide pool didn't determine phenotype
```{r}
# ggplot(hustle.meta, aes(umap_1, umap_2, label = peptide.pool, fill = peptide.pool, colour = peptide.pool)) +
#   geom_point(size = 3, alpha = 0.8) +
#   theme_bw()
```





