---
title: "Clonotype information to integrated object"
output: html_notebook
---


```{r opts, echo = F}
knitr::opts_chunk$set(warning = F, message = F)
# knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
#knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=8) 

```


```{r load_libraries, echo = F, message = F, warning = F}
library(Seurat)
library(patchwork)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
library(data.table)
library(DropletUtils)
# devtools::install_github("satijalab/seurat", "seurat5")
# devtools::install_github("satijalab/seurat-data", "seurat5")
# BiocManager::install("DirichletMultinomial")
# install.packages("hdf5r")
# remotes::install_github("mojaveazure/seurat-disk")
# BiocManager::install("TFBSTools")
# remotes::install_github('satijalab/azimuth', ref = 'master')
library(Azimuth)

```


```{r}
integrated <- readRDS("robjects/naive_merged_with_integrated_proliferated_L1_L2.rds")
clonotype <- read.csv2("../Data/HUSTLEseq_mapped_clean.csv")
```

```{r}
integrated@meta.data <- integrated@meta.data %>% 
  mutate(Barcode = rownames(.)) %>% 
  mutate(Barcode = gsub(".*_", "", Barcode))

umap <- integrated@reductions[["umap_cca"]]@cell.embeddings[,1:2]

integrated_df <- data.frame(integrated@meta.data[,c("orig.ident", "Donor_expt", "seurat_clusters", "HTO_classification", "pep.pool", "donor_pep.pool", "Barcode")], umap)

pheno_clono <- left_join(clonotype, integrated_df, by = "Barcode")

#write.csv2(pheno_clono, "tables/phenotype_clonotype_smallset_7k.csv", row.names = F, quote = F)
```

```{r}
# T cells where TCRs were labeled as epitopes
ggplot(pheno_clono,
       aes(x = umapcca_1, y = umapcca_2, color = factor(Epitope.1))) +
  geom_point(alpha = 0.9, size = 0.6) +
  scale_color_discrete(na.value = "gray80") +
  theme_bw()
  
#ggsave("figures/umap_mapped_epitopes.png", dpi = 300)
```

```{r}
pheno_clono %>% 
  filter(Mapped == "TRUE") %>% 
ggplot(.,
       aes(x = umapcca_1, y = umapcca_2, color = factor(Clone.ID))) +
  geom_point(alpha = 0.9, size = 0.6) +
  scale_color_discrete(na.value = "gray80") +
  theme_bw()

pheno_clono %>% 
  filter(Epitope.1 == "24") %>% 
ggplot(.,
       aes(x = umapcca_1, y = umapcca_2, color = factor(Clone.ID))) +
  geom_point(alpha = 0.9, size = 0.6) +
  scale_color_discrete(na.value = "gray80") +
  facet_wrap(.~seurat_clusters) +
  theme_bw()
```


```{r}
# map clonotypes to clusters
table(pheno_clono$Epitope.1)
 #Epitope 7  10  13  18  23  24  28  31  38  57  68  85 
 # cells  8  32   4   7  90 179 146   8  33  24 463   9 

table(pheno_clono$Epitope.1, pheno_clono$seurat_clusters)

  #      0   1   2   3   4   5   6   7
  # 7    6   1   0   0   1   0   0   0
  # 10   0   0  27   0   0   0   0   0
  # 13   0   1   0   0   0   1   0   0
  # 18   0   0   0   0   0   1   0   0
  # 23  27  18   8   0  30   1   0   0
  # 24  73  40  24   1  17  11   0   0
  # 28  13  17  73   0  19   1   0   1
  # 31   3   4   0   0   0   0   0   0
  # 38  12   1   1   0   0  11   0   0
  # 57   0   2   6   1   0   5   0   0
  # 68   7 172 163   1  17  32   0   4
  # 85   0   0   2   0   0   1   0   0
  
ggplot(pheno_clono,
       aes(x = umapcca_1, y = umapcca_2, color = factor(Epitope.1))) +
  geom_point(alpha = 0.7, size = 0.6) +
  scale_color_discrete(na.value = "gray80") +
  facet_wrap(. ~ Epitope.1) +
  theme_bw()
  
#ggsave("figures/umap_mapped_epitopes_to_s.clusters.png", dpi = 300)
```

```{r}
# background or bystander

 table(pheno_clono$Background)

# FALSE  TRUE 
#  3947  3747 

p1 <- ggplot(pheno_clono,
       aes(x = umapcca_1, y = umapcca_2, color = Background)) +
  geom_point(alpha = 0.7, size = 0.6) +
  scale_color_discrete(na.value = "gray80") +
  theme_bw()

table(pheno_clono$Bystander)

# FALSE  TRUE 
#  7522   172 

p2 <- ggplot(pheno_clono,
       aes(x = umapcca_1, y = umapcca_2, color = Bystander)) +
  geom_point(alpha = 0.7, size = 0.6) +
  scale_color_discrete(na.value = "gray80") +
  theme_bw()

p1 + p2

#ggsave("umap_background_bystander.png", dpi = 300, width = 30, height = 20, units = "cm")

table(pheno_clono$Background, pheno_clono$Epitope.1)
# 
#          7  10  13  18  23  24  28  31  38  57  68  85
#   FALSE   8  32   4   7  90 179 146   8  33  24 463   9
#   TRUE    0   0   0   0   0   0   0   0   0   0   0   0

table(pheno_clono$Background, pheno_clono$seurat_clusters)

  #         0    1    2    3    4    5    6    7
  # FALSE  215  512  904  539  138  752    0    6
  # TRUE  1418  792  290   46  815   49    0    5
```
